# Generated by Django 4.1.3 on 2022-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_issue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist',
        ),
    ]
