# Generated by Django 4.1.3 on 2022-11-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_artist_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='series_id',
            new_name='series',
        ),
    ]
