# Generated by Django 4.1.3 on 2022-11-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_artist_id_issue_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
