# Generated by Django 4.1.3 on 2022-11-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_artist_issue_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='series',
            new_name='series_id',
        ),
    ]
