# Generated by Django 4.1.3 on 2022-11-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_series_issue_series_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='user_id',
        ),
    ]
